### ISSUE TITLE
Support for read only repository?

### ISSUE THREAD

**Issue by bdongus** [urfnet/URF.Core#12]
I would like to have support for read only repositories. Implementing something like CQS needs no insert, delete or update in the "Q" part. The injected context could then be an untracked one, which IMHO improves performance.

**Comment by tonysneed** [comment]
There is support for this kind of thing in the new architecture.  So basically you just add the URF.Core.EF package and don't add the *.Trackable packages.  Then you will be able to use URF without change tracking.  The overhead involved change-tracking (graphs), vs write vs read-only.

**Comment by lelong37** [comment]
Yes, or you could just create your own e.g. IRepositoryX<TEntity>, the concrete implementation of IRepositoryX can easily be injected with URF's IRepository<TEntity> however only exposing what you consider "read-only" or on the "Q" side of things. For the other side CQRS (write related), simply create IRepositoryY<TEntity> (same pattern, Decorator Pattern) and inject IRepository<TEntity> into it's ,concrete implementation, and only expose what you consider non-readonly methods. With URF.Core, we've made pretty much everything public & virtual (overridable) so teams/projects can customize to their needs. With, this we'll go ahead and add a user story to allow disabling change-tracking if you're using entire URF.Core, however how edge cases where you don't want tracking for performance reasons, we'll shoot to have this for RC1 for URF.Core which is very soon, thanks.
