### ISSUE TITLE
Abstracting the exceptions 

### ISSUE THREAD

**Issue by bdongus** [urfnet/URF.Core#13]
"DbUpdateConcurrencyException" in the example is EF specific. Abstracting ORM exceptions would remove the EF dependency from the business logic layer. That way another ORM or technology could be used in the lower layer. Or did I get something wrong?

**Comment by tonysneed** [comment]
Certainly this is an option for the individual developer (rather than the framework).

**Comment by lelong37** [comment]
Agree w/ Tony on this one, you could choose to throw any other exception or even you own, closing this.
