### ISSUE TITLE
Delete Action

### ISSUE THREAD

**Issue by sreul** [urfnet/URF.Core#17]
Hi, I'm new to URF/URF.Core and I used your Northwind example to get started. The Delete Action seems not to work.  I run a DELETE http://localhost:2791/odata/Products(77)' via Postman, but that did not delete key 77 from the database (SQLSERVER). Hope you can reproduce the issue or tell me how to execute the Delete Action correctly. Thanks in advance!
![urf delete](https://user-images.githubusercontent.com/26249914/36749085-061d8458-1bfa-11e8-8839-7942eb3b6311.png)

**Comment by lelong37** [comment]
Yes, we're tracking this issue (https://github.com/urfnet/URF.Core/issues/15), should have a fix released tomorrow, will update this issue, once this is completed.

**Comment by lelong37** [comment]
Please see https://github.com/urfnet/URF.Core/issues/15#issuecomment-369136557, thanks!

**Comment by sreul** [comment]
Hi @lelong37, the Delete Action now works. Thank you!

**Comment by lelong37** [comment]
Your very welcome :)

**Comment by sreul** [comment]
Please have a look at namespace "URF.Core.Abstractions". Sometimes you write "URF..." and sometimes "Urf...". Maybe this is not what you want? :)
![urfnamespace](https://user-images.githubusercontent.com/26249914/36790508-52d54c54-1c95-11e8-8c4a-af56f3994498.png)
