### ISSUE TITLE
Delete on ITrackableRepository

### ISSUE THREAD

**Issue by ferryferry** [urfnet/URF.Core#18]
Hi,

Today I was testing with URF.Core..

I created a delete API function to delete a tweet from the database
![image](https://user-images.githubusercontent.com/17270672/36829650-78e51704-1d20-11e8-9638-6ecdfaf79d85.png)

After the function has ran, it gives me an "200" Ok response, but when I check the database, the tweet with id 1 is still there.

Am I doing something wrong?

**Comment by lelong37** [comment]
@ferryferry we've ran integration tests on our side, and it is successful inside. 

- Could you check to make sure you're running latest URF.Core packages?
- If this isn't resolved after updating to URF.Core latest NuGet packages, could you be so kind to submit a PR with it failing so we can reproduce what your experiencing on your side?

Before:
![image](https://user-images.githubusercontent.com/4691404/37092034-e23e1364-21cf-11e8-86ae-a0ac71599533.png)

Debugging:
![2018-03-07_6-16-11](https://user-images.githubusercontent.com/4691404/37091976-b51a1496-21cf-11e8-9a3d-436df44d9cbe.gif)

After:
![image](https://user-images.githubusercontent.com/4691404/37092071-03018734-21d0-11e8-82b6-761c4bc1f3df.png)

**Comment by tonysneed** [comment]
@lelong37 Do we call apply changes in the delete method?

**Comment by tonysneed** [comment]
Now that I think about it, maybe it’s better if we just updated the individual entity stayed here?

**Comment by lelong37** [comment]
@ferryferry we've also just updated URF.Sample which has Delete Action https://github.com/urfnet/URF.Core.Sample.

**Comment by tonysneed** [comment]
Related: #19.  Does not address this issue per se, but makes the behavior more consistent.
