### ISSUE TITLE
Change Track is not happening while using Patch

### ISSUE THREAD

**Issue by noufionline** [urfnet/URF.Core#20]
I was just trying your sample. 

First of all, it doesn't update without explicitly specifying _productService.ApplyChanges() before calling unitOfWork.SaveChangesAsync().

Even though I only updated one property it updates every single property in the table.

Am I missing something?

**Comment by lelong37** [comment]
There was a PR that issued with a minor refactor, and there was a bug that was introduced during the merge, this has been hot-fixed, released and URF.Core NuGet Packages RC1 has been released with the hot-fix and live demo has been redployed with RC1 bits.

* https://github.com/urfnet/URF.Core/releases/tag/v1.0.0-rc1
* https://www.nuget.org/packages?q=urf.core
* https://github.com/urfnet/URF.Core.Sample
