### ISSUE TITLE
Insert called even in update and delete methods

### ISSUE THREAD

**Issue by noufionline** [urfnet/URF.Core#21]
Hi there,

I am a bit confused here.

In your repository code 

```csharp
 public virtual void Insert(TEntity item)
            => Context.Entry(item).State = EntityState.Added;
```
and at the same time in the Trackable Code
```csharp

 public override void Insert(TEntity item)
        {
            item.TrackingState = TrackingState.Added;
            base.Insert(item);
        }

        public override void Update(TEntity item)
        {
            item.TrackingState = TrackingState.Modified;
            base.Insert(item);
        }

        public override void Delete(TEntity item)
        {
            item.TrackingState = TrackingState.Deleted;
            base.Insert(item);
        }

```
Even for Delete and Update methods Insert is called.

**Comment by celestialtek** [comment]
Oh, I had to clone and modified these code, I think author copy & paste in code 💃

**Comment by lelong37** [comment]
There was a PR that issued with a minor refactor, and there was a bug that was introduced during the merge, this has been hot-fixed, released and URF.Core NuGet Packages RC1 has been released with the hot-fix and live demo has been redployed with RC1 bits.

* https://github.com/urfnet/URF.Core/releases/tag/v1.0.0-rc1
* https://www.nuget.org/packages?q=urf.core
* https://github.com/urfnet/URF.Core.Sample
