### ISSUE TITLE
Missing ThenInclude

### ISSUE THREAD

**Issue by nkovacic** [urfnet/URF.Core#26]
In EF6 you could include nested navigation properties using the regular Include method, but in EF Core this is not possible anymore.
Is this usercase supported in URF.Core?

**Comment by tonysneed** [comment]
This question pertains to entity framework, not you RF. But EF core does support nested includes. Please see the EF core documentation.

**Comment by nkovacic** [comment]
I am asking in the context of Repository and Query class in URF.Core. 
https://github.com/urfnet/URF.Core/blob/master/URF.Core.EF/Query.cs#L25

In URF.EF6 you could use .Include(q => q.Property.Select(property => property.NavigationProperty) to use nested eager load of entities. This is not possible in currently in URF.Core because EF.Core has disabled this type of nested Include and instead uses .Include().ThenInclude() syntax.

**Comment by tonysneed** [comment]
What’s wrong with the new syntax? Maybe provide an example?

**Comment by nkovacic** [comment]
https://docs.microsoft.com/en-us/ef/core/querying/related-data#including-multiple-levels

How can this example by translated to URF.Core Repository pattern?
Because as I mentioned the Query class in URF.Core is missing .ThenInclude method.

**Comment by tonysneed** [comment]
@lelong37 You want to take a stab at this?

**Comment by lelong37** [comment]
Sure, reviewing...

**Comment by nkovacic** [comment]
Any update on this? It is a important feature and we are currently using Include with magic strings as a workaround.

**Comment by nkovacic** [comment]
@lelong37 the referenced test only includes one level deep, where .ThenInclude is used after that.
A quick fix, which we are currently using is converting .Include nested expression to string path as described on [https://stackoverflow.com/questions/46374252/how-to-write-repository-method-for-theninclude-in-ef-core-2](https://stackoverflow.com/questions/46374252/how-to-write-repository-method-for-theninclude-in-ef-core-2)

**Comment by lelong37** [comment]
@tonysneed can you take a look at this? I took a look at we’ll need to keep a list of includes that are relational (includes, thenIncludes) and iterate through them and add them to IQueryable before binding while in deferred execution.

**Comment by tonysneed** [comment]
I’ll have a look tomorrow.

**Comment by tonysneed** [comment]
Resolved by #28.
