### ISSUE TITLE
Stored Procedures with URF.Core

### ISSUE THREAD

**Issue by ydlkrishna** [urfnet/URF.Core#36]
Is there any way to use Stored Procedures and binding to complex entity types which is available in URF.Net? If not any workarounds as we have lot of business logic already implemented in SQL Server DB and make use of it for new application development? Or we should go back and use EF6 with URF.Net or the combination of EF6 for SPs and EF Core for regular table entities or some else...

Thanks in advance,
Krishna.

**Comment by tonysneed** [comment]
Just published NuGet packages yesterday for URF.Core v1 RTM.
