### ISSUE TITLE
The current CSharpHelper cannot scaffold literals of type 'Microsoft.EntityFrameworkCore.Metadata.Internal.DirectConstructorBinding'. Configure your services to use one that can.

### ISSUE THREAD

**Issue by vialeda** [urfnet/URF.Core#38]
Since the RC2 version until the official 1.0.0 I got a problem with the migration system with Visual Studio. Once I install the package I get this message when I add migration: The current CSharpHelper cannot scaffold literals of type 'Microsoft.EntityFrameworkCore.Metadata.Internal.DirectConstructorBinding'. Configure your services to use one that can.
I do not have the error message if I use the RC1 version. Did you know what can be done to avoid this error?

Best regards,
David

**Comment by tonysneed** [comment]
What version of the .NET Core SDK are you using?

**Comment by vialeda** [comment]
2.1.200

**Comment by tonysneed** [comment]
There's your problem.  You need to install the SDK for .NET Core 2.1.3 ( currently in RC): https://www.microsoft.com/net/download/dotnet-core/sdk-2.1.300-rc1

**Comment by tonysneed** [comment]
URF.Core v1 depends on EF Core 2.1, which is now RC but will RTM any day now.

**Comment by vialeda** [comment]
I just finished the installation and I got the same error... Do I have to clear the cache of something?

**Comment by tonysneed** [comment]
I'll try to reproduce this on my end.  Can you post a sample repo on GitHub?

**Comment by vialeda** [comment]
Thank you tonysneed, I updated all other packages as well to the 2.1RC. It's now working. Thank you!!

**Comment by tonysneed** [comment]
My pleasure!
