### ISSUE TITLE
CancellationToken

### ISSUE THREAD

**Issue by Domitnator** [urfnet/URF.Core#42]
Hi Guys,

The Query class (URF.Core.EF\Query.cs) has a bunch of methods. I noticed that for some of the the CancellationToken is set to default but not for all:

![image](https://user-images.githubusercontent.com/13468638/41412949-ebfe2ee2-6fe1-11e8-8a0e-0cc0ded1d635.png)

Is that done with a specific reason?

I'm using the FirstOrDefaultAsync method a lot (for including child properties) and it is quite anoying to supply the CancellationToken everytime.

```
var shipment = await _service
                .Query()
                .Include(s => s.RMAs)
                .FirstOrDefaultAsync(s => s.Id == id, new System.Threading.CancellationToken());
```
Thanks in advance,

Alfred

**Comment by lelong37** [comment]
@Domitnator could you be so kind to issue a PR setting CancellationToken = default?

**Comment by Domitnator** [comment]
Fixed in https://github.com/urfnet/URF.Core/releases/tag/v2.2.0
