### ISSUE TITLE
Automatic tracking state

### ISSUE THREAD

**Issue by ydlkrishna** [urfnet/URF.Core#44]
Do we have any option to determine the state automatically? for e.g. a ProductDTO is received from the consumer and mapped to the Product entity fetched from DB by using Automapper and in this case the Tracking state of the Product entity should be automatically changed to Modified (,if the Product properties are changed by ProductDTO) ? or we should always set the Tracking State manually for each entity? Please advise.

**Comment by tonysneed** [comment]
The way change tracking works is that tracking state is set on the client (either manually or using a change tracker).  The TrackingState property on each entity is then serialized to the service.  At that point, your automapper should copy it from the DTO to the entity.  No changes are necessary on the service side.

**Comment by ydlkrishna** [comment]
@tonysneed , yeah! I got that. do you have any recommondation or examples on how we can implement the TrackingState at client side? I see your JS client side library is still in alpha release. 
If we are not able to set the tracking state at client side, what workarounds we have to handle this in serer side?

**Comment by tonysneed** [comment]
Do you have a JS client? If so I suggest trying the npm package. Even though it is in alpha, it does work.

@lelong37 Do you want to work on a sample that includes client-side change tracking in Angular?

**Comment by lelong37** [comment]
Although this is possible to surface entity Tracking state to ng and react apps via Web Api, Urf.Core doesn't officially support this. All you need to do is serialize the Entity State to ng when you make your Web Api call, closing issue.
