### ISSUE TITLE
Transactional integrity using oData batch

### ISSUE THREAD

**Issue by ugomonte** [urfnet/URF.Core#46]
hi, 

I'm trying to use odata's batch functions with net core 2.1.

on API:
...
app.UseODataBatching ();
routeBuilder.MapODataServiceRoute ("ODataRoute", "odata", oDataConventionModelBuilder.GetEdmModel (), new DefaultODataBatchHandler ());

on Client:
...
var responses = await container.SaveChangesAsync (SaveChangesOptions.BatchWithSingleChangeset);

The container calls the various API controllers but the transactional integrity is not managed and if an update goes wrong it does not roll back.

Should UnitOfWork not be responsible for completing the transaction?
Do I have to set some parameters in the api project setup?

Thank you
Ugo

**Comment by lelong37** [comment]
EF Core manages Transactions out of the box, @tonysneed could you confirm? So we made a design decision not to support w/ Urf.Core since it would be redundant. However, you can easily implement this (from previous version of Urf: https://github.com/urfnet/URF.NET/wiki/Transactions).

**Comment by tonysneed** [comment]
When SaveChanges is called in a controller, EF will put all changes in a single transaction. If you want to include multiple calls to SaveChanges in a single transaction, then they need to be wrapped in a TransactionScope within a using block. This is documented for EF Core [here](https://docs.microsoft.com/en-us/ef/core/saving/transactions). @lelong37 Could this be done at the service level?

**Comment by ugomonte** [comment]
I seem to have found a solution.

Using the appreciated indications https://stackoverflow.com/questions/21373362/transactional-batch-processing-with-odata 
I implemented a new class inherited from DefaultODataBatchHandler in which I override ProcessBatchAsync using TransactionScope like this:

public class TransactionScopeODataBatchHandler : DefaultODataBatchHandler
    {
        private ILoggerManager _logger;
        public TransactionScopeODataBatchHandler(ILoggerManager logger)
        {
            _logger = logger;
        }

        public override async Task ProcessBatchAsync(HttpContext context, RequestDelegate nextHandler)
        {
            using (TransactionScope scope = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
            {
                try
                {
                    var originBody = context.Response.Body;

                    var newBody = new MemoryStream();

                    context.Response.Body = newBody;

                    await base.ProcessBatchAsync(context, nextHandler); //.ConfigureAwait(false);

                    newBody.Seek(0, SeekOrigin.Begin);

                    string json = new StreamReader(newBody).ReadToEnd();

                    context.Response.Body = originBody;

                    //json.Replace("", ""); //here you can modify. But before writing to Response, it helps to set the Content Length property

                    string modifiedJson = json;

                    await context.Response.WriteAsync(modifiedJson);

                    if (context.Response.StatusCode == 200 && !json.Contains("Internal Server Error"))
                    {
                        // Commit transaction if all commands succeed, transaction will auto-rollback
                        // when disposed if either commands fails
                        // The Complete method commits the transaction. If an exception has been thrown,
                        // Complete is not  called and the transaction is rolled back.
                        scope.Complete();
                    }
                    else
                    {
                        // nothing to do
                    }
                }
                catch (Exception ex)
                //catch (TransactionAbortedException ex)
                {
                    _logger.LogError(context.TraceIdentifier.ToString() + " " + "TransactionScopeODataBatchHandler. TransactionAborted. " + ex.InnerException.Message.ToString());
                }
            }
        }
    }

----------
In the Startup in the routeBuilder configuration I replaced the default class with this new class.

   var odataBatchHandler = new TransactionScopeODataBatchHandler(logger);

   app.UseMvc(routeBuilder =>
   {
      routeBuilder.Select().Expand().Filter().OrderBy().MaxTop(1000).Count();

      routeBuilder.MapODataServiceRoute("ODataRoute", "odata", GetEdmModel(app), odataBatchHandler);
      routeBuilder.EnableDependencyInjection();
   });

----------
In the client I save the updated data using this command:
var responses = await container.SaveChangesAsync (SaveChangesOptions.BatchWithSingleChangeset);

Please highlight me if you see problems. Thank you very much.

**Comment by tonysneed** [comment]
Closing as resolved. Thanks!
