### ISSUE TITLE
How to use Transactions in this framework 

### ISSUE THREAD

**Issue by ahmedjalalmalik** [urfnet/URF.Core#47]
I am trying to use Transactions in this but there is no such example  and implementation. whereas in URF.Net there is an implementation of that ass shown below 
```

using System;
using System.Data;
using Repository.Pattern.Repositories;
using TrackableEntities;

namespace Repository.Pattern.UnitOfWork
{
    public interface IUnitOfWork
    {
        int SaveChanges();
        int ExecuteSqlCommand(string sql, params object[] parameters);
        IRepository<TEntity> Repository<TEntity>() where TEntity : class, ITrackable;
        int? CommandTimeout { get; set; }
        void BeginTransaction(IsolationLevel isolationLevel = IsolationLevel.Unspecified);
        bool Commit();
        void Rollback();
    }
}
```

**Comment by tonysneed** [comment]
@ahmedjalalmalik EF Core gives you a transaction for free when you call `SaveChangesAsync`, so there is no need to explicitly begin a transaction, unless you wish to alter the default transaction settings (such as timeout or isolation level).

In case you do need to change transaction characteristics, then the best practice is to use [System.Transactions](https://docs.microsoft.com/en-us/ef/core/saving/transactions#using-systemtransactions), support for which was added in EF Core 2.1.
