### ISSUE TITLE
Possible SingleOrDefaultAsync issue?

### ISSUE THREAD

**Issue by Domitnator** [urfnet/URF.Core#48]
Hi Guys,

I bumped into a really strange issue when working on a project while using URF.core. I noticed that in my unit test a really simpel assert failed. But because there was a lot of custom code involved i first thought it was a mistake on my side so i skipped over it. Today I ran into the same issue again so I updated my fork of urf.core and added a simpel unit test:

```
[Fact]
        public async Task Product_Should_Not_Be_Null_After_A_Contains_Query()
        {
            // Arrange
            var repository = new Repository<Product>(_fixture.Context);

            // Act
            var products = await repository.Query().Where(p => p.ProductId == 1).SelectAsync();
            
            // Assert
            Assert.NotNull(products);

            // Act
            var product = await repository.Query().SingleOrDefaultAsync(s => s.ProductId == 2, new System.Threading.CancellationToken());

            // Assert
            Assert.NotNull(product);
        }
```

To my suprise this unit test is failing as well! Am i making a mistake or doing something wierd?

You can clone my fork to see it failing: https://github.com/Domitnator/URF.Core

I believe there is something going wrong in the SingleOrDefaultAsync because if i would replace that line with FindAsync:

```
[Fact]
        public async Task Product_Should_Not_Be_Null_After_A_Contains_Query()
        {
            // Arrange
            var repository = new Repository<Product>(_fixture.Context);

            // Act
            var products = await repository.Query().Where(p => p.ProductId == 1).SelectAsync();
            
            // Assert
            Assert.NotNull(products);

            // Act
            var product = await repository.FindAsync(2);

            // Assert
            Assert.NotNull(product);
        }
```
It works!

But it also works when i also request product with id 2 in the first query:

```
[Fact]
        public async Task Product_Should_Not_Be_Null_After_A_Contains_Query()
        {
            // Arrange
            var repository = new Repository<Product>(_fixture.Context);

            // Act
            var products = await repository.Query().Where(p => new List<int> { 1, 2 }.Contains(p.ProductId)).SelectAsync();
            
            // Assert
            Assert.NotNull(products);

            // Act
            var product = await repository.Query().SingleOrDefaultAsync(s => s.ProductId == 2, new System.Threading.CancellationToken());

            // Assert
            Assert.NotNull(product);
        }
```
So i'm not quite sure if it has anything to do with the SingleOrDefaultAsync method.

Hopefully you can help me out.

**Comment by GitHubAre** [comment]
In the Repository implementation they have something like:
```
        private readonly IQuery<TEntity> _query;

        public Repository(DbContext context)
        {
            Context = context;
            Set = context.Set<TEntity>();
            _query = new Query<TEntity>(this);
        }

public virtual IQuery<TEntity> Query() => _query;
```

So when you use Query() and some subsequent query operations, it will remember the expressions because this instance is used throughout the existence of the Repository.
Which is wrong in my opinion, because queries are supposed to be fire and forget.
I have fixed it by removing the local field from Repository class and using this instead:
`public virtual IQuery<TEntity> Query() => new Query<TEntity>(this);`
This way every time I call Query(), the query is not caching expression trees from past execution.

**Comment by Domitnator** [comment]
Great catch! Will try to add something similar to my code. But i'd rather not change URF internals as this would force me to add project references instead of nuget packages.

@tonysneed @lelong37 How do you guys feel about this? If you want i can make a PR for this issue?

**Comment by tonysneed** [comment]
@Domitnator, yes I think a PR would be good.

**Comment by lelong37** [comment]
@Domitnator if you could be so kind to issue a PR on this, that would be great.

**Comment by GeorgeWieggers** [comment]
Any idea when this pull request will be merged? I'm facing the same issue over here as well.

**Comment by Domitnator** [comment]
Fixed in https://github.com/urfnet/URF.Core/releases/tag/v2.2.0
