### ISSUE TITLE
How to store Header and Detail relation data?

### ISSUE THREAD

**Issue by vinayaroraincedo** [urfnet/URF.Core#49]
I'm trying to store Header and Detail relation data using Insert function for URF.Core.Services.

 _notificationService.Insert(
                new Notifications()
                {
                    ClientId = command.ClientId,
                    ClientNotificationTemplateId = command.ClientNotificationTemplateId,
                    ConsumerId = command.ConsumerId,
                    NotifiationType = command.NotifiationType,
                    NotificationDetails = new List<NotificationDetails>()
                     {
                         new NotificationDetails(){ Body = command.Body, NotifiationType = command.NotifiationType, RecepientAddress = command.RecepientAddress
                         , Subject = command.Subject, CreatedOn = DateTime.Now, CreatedBy = 123, IsActive = true, IsDeleted = false, TrackingState = TrackingState.Added}
                     },
                    Status = command.Status,
                    CreatedOn = DateTime.Now,
                    CreatedBy = 602737,
                    IsActive = true,
                    IsDeleted = false

                });

Do I have to set some parameters in the service call?

**Comment by vinayaroraincedo** [comment]
I've go thorough the #37 but it doesn't help me. I've made a ApplyChanges() call on the parent object but savedChanges gives me 1.

 _notificationService.Insert(notification);
_notificationService.ApplyChanges();
int savedChanges = await _unitOfWork.SaveChangesAsync();

**Comment by Crazybutch** [comment]
@vinayaroraincedo I'm creating the Id in my Code Id = Guid.NewGuid(); because SaveChanges just returns the count of saved datasets (rows?)

I set the Id on my Dto - AutoMapper to -> Entity and after successful SaveChanges() > 0 I know that my self created Id is valid.

**Comment by lelong37** [comment]
This is an EF issue, unrelated to URF, closing.
