### ISSUE TITLE
support for multiple context

### ISSUE THREAD

**Issue by svachha** [urfnet/URF.Core#52]
how to use this framework when you have multiple database to target in same project. 

Repository takes Dbcontext but only the last DI registration will be used.

Ex. 
services.AddScoped<DbContext, AContext>();
            services.AddScoped<DbContext, BContext>();
            services.AddScoped<IUnitOfWork, UnitOfWork>();
service.AddScoped<IRepository<TableA>,Repository<TableA>();
only BContext will be resolved

any help appriciated.

**Comment by aliBordbar1992** [comment]
any updates on this one?

**Comment by tonysneed** [comment]
@aliBordbar1992 This article offers a good solution to the problem of resolving multiple implementations: http://hamidmosalla.com/2018/06/30/dependency-injection-conditional-resolving-of-multiple-implementation-of-interface/

**Comment by tonysneed** [comment]
@aliBordbar1992 @svachha I completed a sample with all the needed code for using multiple DbContexts with URF.Core. Check it out: https://github.com/urfnet/URF.Core.Sample.MultiContext.

**Comment by lelong37** [comment]
Thanks @tonysneed , awesome implementation, closing this issue.
