### ISSUE TITLE
Why there is no async Insert and update methods

### ISSUE THREAD

**Issue by AJMalik007** [urfnet/URF.Core#55]
I am trying to use this framework but when I look into it I have found many async methods but not insert and update my question is that why there is no async insert and update method is there is any logic behind it

**Comment by tonysneed** [comment]
Insert and update do not touch the database, there is therefore no need for async on those methods — only on saving changes. It may be counter intuitive, but for EF these methods only mark the entity as Added or Modified. No changes are persisted until they are saved to the database in an atomic transaction.
