### ISSUE TITLE
FirstOrDefaultAsnyc() 

### ISSUE THREAD

**Issue by khizranAhmad** [urfnet/URF.Core#58]
I am trying to get user by email I found following ways to get user using 'FirstOrDefaultAsync()'

public async Task<User> GetUserByEmail(string email)
{
        var result = await this.Repository.Query().FirstOrDefaultAsync(x=>x.Email==email, default); 
        return result;
 }
![InkedScreenshot_1_LI](https://user-images.githubusercontent.com/47734172/61772815-9db16500-ae0c-11e9-892e-9d3d4c445cfb.jpg)

public async Task<User> GetUserByEmail_V2(string email)
{
   var result = await this.Repository.Query().FirstOrDefaultAsync(x => x.Email == email, new 
          System.Threading.CancellationToken());
    return result;
}

My Question is why we need to pass predicate and cancelation token in extensuion method? Because I never used predicate in FirstOrDefault extension method.

**Comment by somewhatlogical** [comment]
The FirstOrDefaultAsync() and others are not extension methods.  I assume this was done to preserve extensibility, though am not quite sure if that is needed for this specific instance

**Comment by somewhatlogical** [comment]
Also, of course, note that you can easily declare the extension methods yourself if this is an issue, too.

**Comment by tonysneed** [comment]
@khizranAhmad You have a good point, that `IQuery` should have overloads of `FirstOrDefaultAsync` and `SingleOrDefaultAsync` that omit the predicate. As a workaround, just supply a predicate that returns `true`. You can leave out `cancellationToken` because it's optional anyway.

**Comment by tonysneed** [comment]
Fixed by #72.
