### ISSUE TITLE
Repository.GetRepository<T>

### ISSUE THREAD

**Issue by peterdw** [urfnet/URF.Core#63]
Where can I achieve the following URF.NET functionality in URF.Core ?
Getting another repository B from within repository A with this method:

public interface IRepository<TEntity> where TEntity : class, ITrackable
    {
        ...
        **IRepository<T> GetRepository<T>() where T : class, ITrackable;**
    }

**Comment by ozturkfatih** [comment]
Hi Peter,
You can look at sample [V3 ](https://github.com/urfnet/URF.Core.Sample.v3). Implemantation URF.Core Unit of Work.

**Comment by tonysneed** [comment]
@peterdw Did this answer your question?
