### ISSUE TITLE
Primary key is not tracked when Insert multiple entity with single SaveChangesAsync() on .Net Core 3.0

### ISSUE THREAD

**Issue by najrul-islam** [urfnet/URF.Core#68]
Recently we upgrade our API from .Net Core 2.2 to 3.1 and URF.Core.EF.Trackable 2.2.0 to 3.0.0. In .Net Core 2.2 and URF.Core.EF.Trackable 2.2.0 everything was working fine. But after upgrade to URF.Core.EF.Trackable 3.0.0, when we Insert multiple entity and use the first entity Primary Key auto increment Id in others entity Foreign Key reference with single SaveChangesAsync() get the error. After execute Insert statement the Primary Key Id of that Entity is still 0 but in URF.Core.EF.Trackable 2.2.0 it was set to -2147482647.
Is there any plan to fix this issue?
For More : https://github.com/dotnet/efcore/issues/12378
https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#notrackingresolution

**Comment by tonysneed** [comment]
@najrul-islam Thanks for submitting the issue. As you note, this is a breaking change from EF Core 2.x to 3.x. Perhaps the best course of action would be to create a failing test to replicate this condition. Is this something you thing you might be able to do?

**Comment by tonysneed** [comment]
Closing this as we do not have a failing test.
