### ISSUE TITLE
Graphics

### ISSUE THREAD

**Issue by tonysneed** [urfnet/URF.Core#8]
![2018-02-09_0-16-15](https://user-images.githubusercontent.com/2836367/36233036-c501125a-11a9-11e8-972f-8c673534760a.png)

**Comment by lelong37** [comment]
![image](https://user-images.githubusercontent.com/4691404/36338744-aec7ce78-137c-11e8-8a2b-ec82befa64b2.png)

**Comment by tonysneed** [comment]
Neato
